name: 'Check linting'

on: push

jobs:
  tests:
    runs-on: ubuntu-latest
  container:
    image: ghcr.io/tourmalinecore/dev-container/dev-container-app:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Check Linting
        run: ./linting-scripts/check_lint.sh

